language: erlang
notifications:
  webhooks: http://basho-engbot.herokuapp.com/travis?key=cf2b9b83873cc2de2a01fad26e1c98cf2882fb02
  email: eng@basho.com
script: "make dialyzer xref test"
otp_release:
  - R16B02
